<?php
/**
 * Overrides the alt text generated by theme.
 *
 * @package AltTextManager
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ATM_Override_Alt_Text {

	private static $instance = null;

	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	private function __construct() {
	    add_filter( 'wp_get_attachment_image_attributes', array( $this, 'override_alt_text' ), 20, 2 );
	}

	public function override_alt_text( $attr, $attachment ) {
		$always_use_alt_text = ATM_Settings::get_option( 'always_use_alt_text' );

		if ($always_use_alt_text) {
			// Real alt text stored in the Media Library
			$alt = get_post_meta( $attachment->ID, '_wp_attachment_image_alt', true );

			// Only override when a real alt exists
			if ( ! empty( $alt ) ) {
				$attr['alt'] = esc_attr( trim( strip_tags( $alt ) ) );
			}
		}
        return $attr;
    }
}
